name: Daily Commit

on:
  schedule:
    - cron: "0 9 * * *"   # Runs every day at 9:00 UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update activity log
        run: |
          echo "$(date)" >> activity.log
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add activity.log
          git commit -m "chore: daily activity [skip ci]" || echo "No changes"
          git push
